In [8]:
import numpy as np
import pandas as pd

In [2]:
water = np.load("water.npy")

In [4]:
locs = np.load("locs.npy")
time = np.load("time.npy")

In [10]:
csv = pd.read_csv("Ian Events.csv")

In [17]:
startEndTimes = csv[["BEGIN_DATE_TIME", "END_DATE_TIME"]].astype("datetime64[s]")

In [46]:
filters = np.apply_along_axis(lambda x: (x[0] < time) & (time < x[1]), 1, startEndTimes.to_numpy())

In [ ]:
nearest_loc = 

In [54]:
lon_lat = csv[["BEGIN_LAT", "BEGIN_LON"]].to_numpy()

In [55]:
lon_lat

array([[ 29.1674, -81.523 ],
       [ 28.5077, -81.4304],
       [ 28.1684, -81.1433],
       [ 28.6479, -81.4181],
       [ 29.2695, -81.1075],
       [ 28.5262, -81.369 ],
       [ 28.5758, -80.874 ],
       [ 28.2603, -81.3187],
       [ 28.7786, -80.9149],
       [ 27.6668, -80.4367],
       [ 28.4627, -80.9253],
       [ 27.2685, -80.3787],
       [ 29.0222, -80.9896],
       [ 28.43  , -81.32  ],
       [ 27.146 , -80.2742],
       [ 27.2101, -80.8416],
       [ 28.6804, -81.4225],
       [ 28.083 , -80.8669],
       [ 29.0222, -80.9896],
       [ 26.3705, -80.1054],
       [ 25.9952, -80.2386],
       [ 25.75  , -80.99  ],
       [ 26.6449, -80.2878],
       [ 26.827 , -81.0781],
       [ 26.7338, -80.3355],
       [ 25.8075, -80.3511],
       [ 26.1123, -80.3297],
       [ 25.8   , -80.72  ],
       [ 26.26  , -80.61  ],
       [ 26.0047, -80.192 ],
       [ 26.5282, -80.068 ],
       [ 25.7711, -80.3354],
       [ 29.5975, -81.2714],
       [ 29.87  , -81.34  ],
       [ 29.39

In [64]:
locs[np.argmin(np.sum(np.square(lon_lat[0] - locs), axis=1))]

array([ 29.47994423, -81.12602997])

In [61]:
def nearest_locs(lon_lat):
    toout = np.zeros(lon_lat.shape[0])
    for i, loc in enumerate(lon_lat):
        toout[i] = np.argmin(np.sum(np.square(loc - locs), axis=1))
    return toout

In [73]:
waterLocIdx = nearest_locs(lon_lat).astype("int64")

In [47]:
filters.shape

(38, 734)

In [68]:
water.shape

(734, 45)

In [83]:
extraCol = []
for i, filter in enumerate(filters):
    locnum = waterLocIdx[i]
    if np.all(filter == False):
        extraCol.append(0)
        continue
    maxWater = np.max(water[:, locnum][filter])
    extraCol.append(maxWater)
extraCol = np.array(extraCol)

In [84]:
extraCol

array([ 2.53023783,  0.70897188,  0.80194635,  0.72373193,  2.43570136,
        0.68516306,  0.72373193,  0.80194635,  0.68516306,  0.24129845,
        0.72000907,  0.24129845,  0.24611221,  0.72373193,  0.23498256,
        0.12013479,  0.24611221,  0.14543086, -0.20778963,  0.7499425 ,
        0.74036589,  0.        ,  0.        ,  0.46031469,  0.75113349,
        0.        ,  0.        ,  0.74036589,  0.        ,  0.74036589,
        0.        ,  0.        ,  0.        ,  0.69888386,  0.        ,
        0.        ,  0.        ,  0.        ])

In [90]:
csv = pd.read_csv("Ian Events.csv")

In [91]:
csv["MAX_WATER"] = extraCol

In [92]:
csv = csv.drop(["Unnamed: 0"], axis=1)
csv.to_csv("Ian Events Water.csv")